# Generated by Django 5.2 on 2025-05-02 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=15, unique=True)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('datos_contacto', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referencia', models.CharField(max_length=50, unique=True)),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('tipo_componente', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=100)),
                ('especificaciones_tecnicas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('componentes', models.ManyToManyField(related_name='productos', to='appEntrega.componente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referencia', models.CharField(max_length=50, unique=True)),
                ('fecha_entrega_estimada', models.DateField()),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('preparado', 'Preparado'), ('entregado', 'Entregado')], default='en_proceso', max_length=20)),
                ('urgencia', models.CharField(choices=[('urgente', 'Urgente'), ('prioritario', 'Prioritario'), ('normal', 'Normal')], default='normal', max_length=20)),
                ('detalles', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='appEntrega.cliente')),
                ('productos', models.ManyToManyField(related_name='pedidos', to='appEntrega.producto')),
            ],
        ),
    ]
