# Generated by Django 5.2.1 on 2025-05-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEntrega', '0002_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='componentes/'),
        ),
    ]
