# Generated by Django 5.2.1 on 2025-05-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEntrega', '0003_componente_archivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documento',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='componente',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
