# Generated by Django 5.2.1 on 2025-05-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEntrega', '0004_delete_documento_remove_producto_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
