# Generated by Django 5.2.1 on 2025-05-21 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEntrega', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('archivo', models.FileField(upload_to='subir/')),
            ],
        ),
    ]
